### PR TITLE
Locations update

### PR DESCRIPTION
**Pull request by vergauwenthomas**
update location 75 - 78 + new locations 85 - 89

### CODE REVIEW

**Comment by vergauwenthomas** [comment]
@bmesuere , The *ID* column in the *data.csv* file for the new stations is set to *unknown*. I will update them when i have the codes.

**Comment by vergauwenthomas** [comment]
@bmesuere, you mentioned that you run [imageoptim](https://github.com/JamieMason/ImageOptim-CLI) on the maps. Since this is only available on OS X I cannot install it on my (Linux) machine. If you know of a similar [mogrify](https://imagemagick.org/script/mogrify.php) command, let me know so I can prepare this myself.

**Comment by vergauwenthomas** [comment]
@bmesuere Er is nog één vlinder die verhuist is. Die zal ik nog toevoegen aan deze request.

**Comment by vergauwenthomas** [comment]
Klaar voor Review/Merge

**Review by bmesuere — APPROVED** [review]

**Pull request merged**
